// Generated by rstantools.  Do not edit by hand.

/*
    compbio-nomeR is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    compbio-nomeR is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with compbio-nomeR.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_background_betabinom_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 17> locations_array__ =
  {" (found before start of program)",
  " (in 'background_betabinom_model', line 13, column 2 to column 32)",
  " (in 'background_betabinom_model', line 14, column 2 to column 31)",
  " (in 'background_betabinom_model', line 33, column 2 to column 17)",
  " (in 'background_betabinom_model', line 34, column 2 to column 16)",
  " (in 'background_betabinom_model', line 35, column 2 to column 65)",
  " (in 'background_betabinom_model', line 36, column 2 to column 126)",
  " (in 'background_betabinom_model', line 22, column 4 to column 120)",
  " (in 'background_betabinom_model', line 21, column 31 to line 23, column 3)",
  " (in 'background_betabinom_model', line 21, column 2 to line 23, column 3)",
  " (in 'background_betabinom_model', line 6, column 2 to column 31)",
  " (in 'background_betabinom_model', line 7, column 18 to column 33)",
  " (in 'background_betabinom_model', line 7, column 2 to column 35)",
  " (in 'background_betabinom_model', line 8, column 20 to column 35)",
  " (in 'background_betabinom_model', line 8, column 2 to column 37)",
  " (in 'background_betabinom_model', line 9, column 20 to column 35)",
  " (in 'background_betabinom_model', line 9, column 2 to column 37)"};
#include <stan_meta_header.hpp>
class model_background_betabinom_model final : public model_base_crtp<model_background_betabinom_model> {
private:
  int n_table_entries;
  std::vector<int> n_total_pos;
  std::vector<int> n_protect_pos;
  std::vector<int> n_frequencies;
public:
  ~model_background_betabinom_model() {}
  model_background_betabinom_model(stan::io::var_context& context__,
                                   unsigned int random_seed__ = 0,
                                   std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_background_betabinom_model_namespace::model_background_betabinom_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 10;
      context__.validate_dims("data initialization", "n_table_entries",
        "int", std::vector<size_t>{});
      n_table_entries = std::numeric_limits<int>::min();
      current_statement__ = 10;
      n_table_entries = context__.vals_i("n_table_entries")[(1 - 1)];
      current_statement__ = 10;
      stan::math::check_greater_or_equal(function__, "n_table_entries",
        n_table_entries, 1);
      current_statement__ = 11;
      stan::math::validate_non_negative_index("n_total_pos",
        "n_table_entries", n_table_entries);
      current_statement__ = 12;
      context__.validate_dims("data initialization", "n_total_pos", "int",
        std::vector<size_t>{static_cast<size_t>(n_table_entries)});
      n_total_pos = std::vector<int>(n_table_entries,
                      std::numeric_limits<int>::min());
      current_statement__ = 12;
      n_total_pos = context__.vals_i("n_total_pos");
      current_statement__ = 13;
      stan::math::validate_non_negative_index("n_protect_pos",
        "n_table_entries", n_table_entries);
      current_statement__ = 14;
      context__.validate_dims("data initialization", "n_protect_pos", "int",
        std::vector<size_t>{static_cast<size_t>(n_table_entries)});
      n_protect_pos = std::vector<int>(n_table_entries,
                        std::numeric_limits<int>::min());
      current_statement__ = 14;
      n_protect_pos = context__.vals_i("n_protect_pos");
      current_statement__ = 15;
      stan::math::validate_non_negative_index("n_frequencies",
        "n_table_entries", n_table_entries);
      current_statement__ = 16;
      context__.validate_dims("data initialization", "n_frequencies", "int",
        std::vector<size_t>{static_cast<size_t>(n_table_entries)});
      n_frequencies = std::vector<int>(n_table_entries,
                        std::numeric_limits<int>::min());
      current_statement__ = 16;
      n_frequencies = context__.vals_i("n_frequencies");
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1;
  }
  inline std::string model_name() const final {
    return "model_background_betabinom_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_background_betabinom_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ alpha_betabinom = DUMMY_VAR__;
      current_statement__ = 1;
      alpha_betabinom = in__.template read_constrain_lb<local_scalar_t__,
                          jacobian__>(0, lp__);
      local_scalar_t__ beta_betabinom = DUMMY_VAR__;
      current_statement__ = 2;
      beta_betabinom = in__.template read_constrain_lb<local_scalar_t__,
                         jacobian__>(0, lp__);
      {
        current_statement__ = 9;
        for (int n = 1; n <= n_table_entries; ++n) {
          current_statement__ = 7;
          lp_accum__.add((stan::model::rvalue(n_frequencies, "n_frequencies",
                            stan::model::index_uni(n)) *
            stan::math::beta_binomial_lpmf<false>(
              stan::model::rvalue(n_protect_pos, "n_protect_pos",
                stan::model::index_uni(n)),
              stan::model::rvalue(n_total_pos, "n_total_pos",
                stan::model::index_uni(n)), alpha_betabinom, beta_betabinom)));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_background_betabinom_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double alpha_betabinom = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      alpha_betabinom = in__.template read_constrain_lb<local_scalar_t__,
                          jacobian__>(0, lp__);
      double beta_betabinom = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      beta_betabinom = in__.template read_constrain_lb<local_scalar_t__,
                         jacobian__>(0, lp__);
      out__.write(alpha_betabinom);
      out__.write(beta_betabinom);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      double mean_beta = std::numeric_limits<double>::quiet_NaN();
      double var_beta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      mean_beta = (alpha_betabinom / (alpha_betabinom + beta_betabinom));
      current_statement__ = 6;
      var_beta = ((alpha_betabinom * beta_betabinom) /
        (stan::math::square((alpha_betabinom + beta_betabinom)) *
        ((alpha_betabinom + beta_betabinom) + 1)));
      out__.write(mean_beta);
      out__.write(var_beta);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ alpha_betabinom = DUMMY_VAR__;
      current_statement__ = 1;
      alpha_betabinom = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, alpha_betabinom);
      local_scalar_t__ beta_betabinom = DUMMY_VAR__;
      current_statement__ = 2;
      beta_betabinom = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, beta_betabinom);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "alpha_betabinom",
        "double", std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "beta_betabinom",
        "double", std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ alpha_betabinom = DUMMY_VAR__;
      current_statement__ = 1;
      alpha_betabinom = context__.vals_r("alpha_betabinom")[(1 - 1)];
      out__.write_free_lb(0, alpha_betabinom);
      local_scalar_t__ beta_betabinom = DUMMY_VAR__;
      current_statement__ = 2;
      beta_betabinom = context__.vals_r("beta_betabinom")[(1 - 1)];
      out__.write_free_lb(0, beta_betabinom);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"alpha_betabinom", "beta_betabinom"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"mean_beta", "var_beta"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{}, std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "alpha_betabinom");
    param_names__.emplace_back(std::string() + "beta_betabinom");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "mean_beta");
      param_names__.emplace_back(std::string() + "var_beta");
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "alpha_betabinom");
    param_names__.emplace_back(std::string() + "beta_betabinom");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "mean_beta");
      param_names__.emplace_back(std::string() + "var_beta");
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha_betabinom\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_betabinom\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mean_beta\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"var_beta\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha_betabinom\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_betabinom\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mean_beta\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"var_beta\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (1 + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * ((1 + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (1 + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * ((1 + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_background_betabinom_model_namespace::model_background_betabinom_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_background_betabinom_model_namespace::profiles__;
}
#endif
#endif
