// Generated by rstantools.  Do not edit by hand.

/*
    compbio-nomeR is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    compbio-nomeR is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with compbio-nomeR.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.26.1-4-gd72b68b7-dirty
#include <stan/model/model_header.hpp>
namespace model_background_mixture_model_namespace {
inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 
stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'background_mixture_model', line 29, column 2 to column 30)",
                                                      " (in 'background_mixture_model', line 32, column 2 to column 40)",
                                                      " (in 'background_mixture_model', line 35, column 2 to column 32)",
                                                      " (in 'background_mixture_model', line 36, column 2 to column 31)",
                                                      " (in 'background_mixture_model', line 39, column 2 to column 22)",
                                                      " (in 'background_mixture_model', line 42, column 2 to column 75)",
                                                      " (in 'background_mixture_model', line 44, column 2 to column 89)",
                                                      " (in 'background_mixture_model', line 48, column 2 to column 28)",
                                                      " (in 'background_mixture_model', line 49, column 2 to column 30)",
                                                      " (in 'background_mixture_model', line 52, column 4 to line 53, column 107)",
                                                      " (in 'background_mixture_model', line 51, column 31 to line 54, column 3)",
                                                      " (in 'background_mixture_model', line 51, column 2 to line 54, column 3)",
                                                      " (in 'background_mixture_model', line 13, column 2 to column 31)",
                                                      " (in 'background_mixture_model', line 14, column 18 to column 33)",
                                                      " (in 'background_mixture_model', line 14, column 2 to column 35)",
                                                      " (in 'background_mixture_model', line 15, column 20 to column 35)",
                                                      " (in 'background_mixture_model', line 15, column 2 to column 37)",
                                                      " (in 'background_mixture_model', line 16, column 20 to column 35)",
                                                      " (in 'background_mixture_model', line 16, column 2 to column 37)",
                                                      " (in 'background_mixture_model', line 19, column 2 to column 46)",
                                                      " (in 'background_mixture_model', line 20, column 2 to column 45)",
                                                      " (in 'background_mixture_model', line 23, column 2 to column 48)",
                                                      " (in 'background_mixture_model', line 24, column 2 to column 47)"};
#include <stan_meta_header.hpp>
class model_background_mixture_model final : public model_base_crtp<model_background_mixture_model> {
private:
  int n_table_entries;
  std::vector<int> n_total_pos;
  std::vector<int> n_protect_pos;
  std::vector<int> n_frequencies;
  double alpha_distrbetaprior_mixcoeff;
  double beta_distrbetaprior_mixcoeff;
  double alpha_distrbetaprior_bg_protect;
  double beta_distrbetaprior_bg_protect;
 
public:
  ~model_background_mixture_model() { }
  
  inline std::string model_name() const final { return "model_background_mixture_model"; }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.26.1-4-gd72b68b7-dirty", "stancflags = "};
  }
  
  
  model_background_mixture_model(stan::io::var_context& context__,
                                 unsigned int random_seed__ = 0,
                                 std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "model_background_mixture_model_namespace::model_background_mixture_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 13;
      context__.validate_dims("data initialization","n_table_entries","int",
          context__.to_vec());
      n_table_entries = std::numeric_limits<int>::min();
      
      current_statement__ = 13;
      n_table_entries = context__.vals_i("n_table_entries")[(1 - 1)];
      current_statement__ = 13;
      current_statement__ = 13;
      check_greater_or_equal(function__, "n_table_entries", n_table_entries,
                             1);
      current_statement__ = 14;
      validate_non_negative_index("n_total_pos", "n_table_entries",
                                  n_table_entries);
      current_statement__ = 15;
      context__.validate_dims("data initialization","n_total_pos","int",
          context__.to_vec(n_table_entries));
      n_total_pos = std::vector<int>(n_table_entries, std::numeric_limits<int>::min());
      
      current_statement__ = 15;
      assign(n_total_pos, nil_index_list(), context__.vals_i("n_total_pos"),
        "assigning variable n_total_pos");
      current_statement__ = 16;
      validate_non_negative_index("n_protect_pos", "n_table_entries",
                                  n_table_entries);
      current_statement__ = 17;
      context__.validate_dims("data initialization","n_protect_pos","int",
          context__.to_vec(n_table_entries));
      n_protect_pos = std::vector<int>(n_table_entries, std::numeric_limits<int>::min());
      
      current_statement__ = 17;
      assign(n_protect_pos, nil_index_list(),
        context__.vals_i("n_protect_pos"), "assigning variable n_protect_pos");
      current_statement__ = 18;
      validate_non_negative_index("n_frequencies", "n_table_entries",
                                  n_table_entries);
      current_statement__ = 19;
      context__.validate_dims("data initialization","n_frequencies","int",
          context__.to_vec(n_table_entries));
      n_frequencies = std::vector<int>(n_table_entries, std::numeric_limits<int>::min());
      
      current_statement__ = 19;
      assign(n_frequencies, nil_index_list(),
        context__.vals_i("n_frequencies"), "assigning variable n_frequencies");
      current_statement__ = 20;
      context__.validate_dims("data initialization",
          "alpha_distrbetaprior_mixcoeff","double",context__.to_vec());
      alpha_distrbetaprior_mixcoeff = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 20;
      alpha_distrbetaprior_mixcoeff = context__.vals_r("alpha_distrbetaprior_mixcoeff")[
          (1 - 1)];
      current_statement__ = 20;
      current_statement__ = 20;
      check_greater_or_equal(function__, "alpha_distrbetaprior_mixcoeff",
                             alpha_distrbetaprior_mixcoeff, 0);
      current_statement__ = 21;
      context__.validate_dims("data initialization",
          "beta_distrbetaprior_mixcoeff","double",context__.to_vec());
      beta_distrbetaprior_mixcoeff = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 21;
      beta_distrbetaprior_mixcoeff = context__.vals_r("beta_distrbetaprior_mixcoeff")[
          (1 - 1)];
      current_statement__ = 21;
      current_statement__ = 21;
      check_greater_or_equal(function__, "beta_distrbetaprior_mixcoeff",
                             beta_distrbetaprior_mixcoeff, 0);
      current_statement__ = 22;
      context__.validate_dims("data initialization",
          "alpha_distrbetaprior_bg_protect","double",context__.to_vec());
      alpha_distrbetaprior_bg_protect = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 22;
      alpha_distrbetaprior_bg_protect = context__.vals_r("alpha_distrbetaprior_bg_protect")[
          (1 - 1)];
      current_statement__ = 22;
      current_statement__ = 22;
      check_greater_or_equal(function__, "alpha_distrbetaprior_bg_protect",
                             alpha_distrbetaprior_bg_protect, 0);
      current_statement__ = 23;
      context__.validate_dims("data initialization",
          "beta_distrbetaprior_bg_protect","double",context__.to_vec());
      beta_distrbetaprior_bg_protect = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 23;
      beta_distrbetaprior_bg_protect = context__.vals_r("beta_distrbetaprior_bg_protect")[
          (1 - 1)];
      current_statement__ = 23;
      current_statement__ = 23;
      check_greater_or_equal(function__, "beta_distrbetaprior_bg_protect",
                             beta_distrbetaprior_bg_protect, 0);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "model_background_mixture_model_namespace::log_prob";
(void) function__;  // suppress unused var warning
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      local_scalar_t__ theta;
      theta = DUMMY_VAR__;
      
      current_statement__ = 1;
      theta = in__.scalar();
      current_statement__ = 1;
      if (jacobian__) {
        current_statement__ = 1;
        theta = stan::math::lub_constrain(theta, 0, 1, lp__);
      } else {
        current_statement__ = 1;
        theta = stan::math::lub_constrain(theta, 0, 1);
      }
      local_scalar_t__ bg_protect_prob;
      bg_protect_prob = DUMMY_VAR__;
      
      current_statement__ = 2;
      bg_protect_prob = in__.scalar();
      current_statement__ = 2;
      if (jacobian__) {
        current_statement__ = 2;
        bg_protect_prob = stan::math::lub_constrain(bg_protect_prob, 0, 1,
                            lp__);
      } else {
        current_statement__ = 2;
        bg_protect_prob = stan::math::lub_constrain(bg_protect_prob, 0, 1);
      }
      local_scalar_t__ alpha_betabinom;
      alpha_betabinom = DUMMY_VAR__;
      
      current_statement__ = 3;
      alpha_betabinom = in__.scalar();
      current_statement__ = 3;
      if (jacobian__) {
        current_statement__ = 3;
        alpha_betabinom = stan::math::lb_constrain(alpha_betabinom, 0, lp__);
      } else {
        current_statement__ = 3;
        alpha_betabinom = stan::math::lb_constrain(alpha_betabinom, 0);
      }
      local_scalar_t__ beta_betabinom;
      beta_betabinom = DUMMY_VAR__;
      
      current_statement__ = 4;
      beta_betabinom = in__.scalar();
      current_statement__ = 4;
      if (jacobian__) {
        current_statement__ = 4;
        beta_betabinom = stan::math::lb_constrain(beta_betabinom, 0, lp__);
      } else {
        current_statement__ = 4;
        beta_betabinom = stan::math::lb_constrain(beta_betabinom, 0);
      }
      {
        Eigen::Matrix<local_scalar_t__, -1, 1> log_theta;
        log_theta = Eigen::Matrix<local_scalar_t__, -1, 1>(2);
        stan::math::fill(log_theta, DUMMY_VAR__);
        
        current_statement__ = 6;
        lp_accum__.add(
          beta_lpdf<propto__>(theta, alpha_distrbetaprior_mixcoeff,
            beta_distrbetaprior_mixcoeff));
        current_statement__ = 7;
        lp_accum__.add(
          beta_lpdf<propto__>(bg_protect_prob,
            alpha_distrbetaprior_bg_protect, beta_distrbetaprior_bg_protect));
        current_statement__ = 8;
        assign(log_theta, cons_list(index_uni(1), nil_index_list()),
          stan::math::log(theta), "assigning variable log_theta");
        current_statement__ = 9;
        assign(log_theta, cons_list(index_uni(2), nil_index_list()),
          stan::math::log((1 - theta)), "assigning variable log_theta");
        current_statement__ = 12;
        for (int n = 1; n <= n_table_entries; ++n) {
          current_statement__ = 10;
          lp_accum__.add(
            (n_frequencies[(n - 1)] *
              log_sum_exp(
                (log_theta[(1 - 1)] +
                  binomial_lpmf<false>(n_protect_pos[(n - 1)],
                    n_total_pos[(n - 1)], bg_protect_prob)),
                (log_theta[(2 - 1)] +
                  beta_binomial_lpmf<false>(n_protect_pos[(n - 1)],
                    n_total_pos[(n - 1)], alpha_betabinom, beta_betabinom)))));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "model_background_mixture_model_namespace::write_array";
(void) function__;  // suppress unused var warning
    (void) function__;  // suppress unused var warning
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      double theta;
      theta = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      theta = in__.scalar();
      current_statement__ = 1;
      theta = stan::math::lub_constrain(theta, 0, 1);
      double bg_protect_prob;
      bg_protect_prob = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      bg_protect_prob = in__.scalar();
      current_statement__ = 2;
      bg_protect_prob = stan::math::lub_constrain(bg_protect_prob, 0, 1);
      double alpha_betabinom;
      alpha_betabinom = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      alpha_betabinom = in__.scalar();
      current_statement__ = 3;
      alpha_betabinom = stan::math::lb_constrain(alpha_betabinom, 0);
      double beta_betabinom;
      beta_betabinom = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      beta_betabinom = in__.scalar();
      current_statement__ = 4;
      beta_betabinom = stan::math::lb_constrain(beta_betabinom, 0);
      vars__.emplace_back(theta);
      vars__.emplace_back(bg_protect_prob);
      vars__.emplace_back(alpha_betabinom);
      vars__.emplace_back(beta_betabinom);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      double theta;
      theta = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      theta = context__.vals_r("theta")[(1 - 1)];
      double theta_free__;
      theta_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      theta_free__ = stan::math::lub_free(theta, 0, 1);
      double bg_protect_prob;
      bg_protect_prob = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      bg_protect_prob = context__.vals_r("bg_protect_prob")[(1 - 1)];
      double bg_protect_prob_free__;
      bg_protect_prob_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      bg_protect_prob_free__ = stan::math::lub_free(bg_protect_prob, 0, 1);
      double alpha_betabinom;
      alpha_betabinom = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      alpha_betabinom = context__.vals_r("alpha_betabinom")[(1 - 1)];
      double alpha_betabinom_free__;
      alpha_betabinom_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      alpha_betabinom_free__ = stan::math::lb_free(alpha_betabinom, 0);
      double beta_betabinom;
      beta_betabinom = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      beta_betabinom = context__.vals_r("beta_betabinom")[(1 - 1)];
      double beta_betabinom_free__;
      beta_betabinom_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      beta_betabinom_free__ = stan::math::lb_free(beta_betabinom, 0);
      vars__.emplace_back(theta_free__);
      vars__.emplace_back(bg_protect_prob_free__);
      vars__.emplace_back(alpha_betabinom_free__);
      vars__.emplace_back(beta_betabinom_free__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("theta");
    names__.emplace_back("bg_protect_prob");
    names__.emplace_back("alpha_betabinom");
    names__.emplace_back("beta_betabinom");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "theta");
    param_names__.emplace_back(std::string() + "bg_protect_prob");
    param_names__.emplace_back(std::string() + "alpha_betabinom");
    param_names__.emplace_back(std::string() + "beta_betabinom");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "theta");
    param_names__.emplace_back(std::string() + "bg_protect_prob");
    param_names__.emplace_back(std::string() + "alpha_betabinom");
    param_names__.emplace_back(std::string() + "beta_betabinom");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"theta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"bg_protect_prob\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alpha_betabinom\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_betabinom\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"theta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"bg_protect_prob\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alpha_betabinom\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_betabinom\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }
    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }
    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  
    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        
};
}
using stan_model = model_background_mixture_model_namespace::model_background_mixture_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_background_mixture_model_namespace::profiles__;
}
#endif
#endif
