// Generated by rstantools.  Do not edit by hand.

/*
    nomeR is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    nomeR is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with nomeR.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_ftp_inference_bg_fixed_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 28> locations_array__ =
  {" (found before start of program)",
  " (in 'ftp_inference_bg_fixed', line 65, column 2 to column 32)",
  " (in 'ftp_inference_bg_fixed', line 67, column 2 to column 69)",
  " (in 'ftp_inference_bg_fixed', line 71, column 2 to column 47)",
  " (in 'ftp_inference_bg_fixed', line 73, column 2 to column 63)",
  " (in 'ftp_inference_bg_fixed', line 75, column 1 to line 84, column 4)",
  " (in 'ftp_inference_bg_fixed', line 37, column 2 to column 13)",
  " (in 'ftp_inference_bg_fixed', line 38, column 8 to column 14)",
  " (in 'ftp_inference_bg_fixed', line 38, column 2 to column 38)",
  " (in 'ftp_inference_bg_fixed', line 39, column 8 to column 14)",
  " (in 'ftp_inference_bg_fixed', line 39, column 2 to column 46)",
  " (in 'ftp_inference_bg_fixed', line 41, column 2 to column 12)",
  " (in 'ftp_inference_bg_fixed', line 42, column 8 to column 13)",
  " (in 'ftp_inference_bg_fixed', line 42, column 2 to column 31)",
  " (in 'ftp_inference_bg_fixed', line 43, column 9 to column 14)",
  " (in 'ftp_inference_bg_fixed', line 43, column 2 to column 32)",
  " (in 'ftp_inference_bg_fixed', line 44, column 2 to column 30)",
  " (in 'ftp_inference_bg_fixed', line 47, column 2 to column 40)",
  " (in 'ftp_inference_bg_fixed', line 49, column 2 to column 23)",
  " (in 'ftp_inference_bg_fixed', line 50, column 2 to column 23)",
  " (in 'ftp_inference_bg_fixed', line 51, column 2 to column 24)",
  " (in 'ftp_inference_bg_fixed', line 52, column 2 to column 28)",
  " (in 'ftp_inference_bg_fixed', line 56, column 9 to column 14)",
  " (in 'ftp_inference_bg_fixed', line 56, column 2 to column 76)",
  " (in 'ftp_inference_bg_fixed', line 58, column 2 to column 67)",
  " (in 'ftp_inference_bg_fixed', line 59, column 2 to column 72)",
  " (in 'ftp_inference_bg_fixed', line 61, column 2 to column 34)",
  " (in 'ftp_inference_bg_fixed', line 65, column 10 to column 15)"};
#include <stan_meta_header.hpp>
class model_ftp_inference_bg_fixed final : public model_base_crtp<model_ftp_inference_bg_fixed> {
private:
  int n_spac;
  std::vector<int> spacings;
  std::vector<std::vector<int>> spacing_counts;
  int n_ftp;
  std::vector<int> ftp_lengths;
  Eigen::Matrix<double,-1,1> ftp_prior_cover_data__;
  double total_cnt_prior_dirich;
  double bg_protect_prob;
  double ftp_protect_min;
  double ftp_protect_max;
  double ftp_protect_mean;
  double ftp_protect_totcount;
  Eigen::Matrix<double,-1,1> ftp_prior_alphas_data__;
  double ftp_protect_alpha;
  double ftp_protect_beta;
  int max_spacing;
  Eigen::Map<Eigen::Matrix<double,-1,1>> ftp_prior_cover{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> ftp_prior_alphas{nullptr, 0};
public:
  ~model_ftp_inference_bg_fixed() {}
  model_ftp_inference_bg_fixed(stan::io::var_context& context__, unsigned int
                               random_seed__ = 0, std::ostream*
                               pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_ftp_inference_bg_fixed_namespace::model_ftp_inference_bg_fixed";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 6;
      context__.validate_dims("data initialization", "n_spac", "int",
        std::vector<size_t>{});
      n_spac = std::numeric_limits<int>::min();
      current_statement__ = 6;
      n_spac = context__.vals_i("n_spac")[(1 - 1)];
      current_statement__ = 7;
      stan::math::validate_non_negative_index("spacings", "n_spac", n_spac);
      current_statement__ = 8;
      context__.validate_dims("data initialization", "spacings", "int",
        std::vector<size_t>{static_cast<size_t>(n_spac)});
      spacings = std::vector<int>(n_spac, std::numeric_limits<int>::min());
      current_statement__ = 8;
      spacings = context__.vals_i("spacings");
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "spacings", spacings, 1);
      current_statement__ = 9;
      stan::math::validate_non_negative_index("spacing_counts", "n_spac",
        n_spac);
      current_statement__ = 10;
      context__.validate_dims("data initialization", "spacing_counts", "int",
        std::vector<size_t>{static_cast<size_t>(n_spac),
          static_cast<size_t>(4)});
      spacing_counts = std::vector<std::vector<int>>(n_spac,
                         std::vector<int>(4, std::numeric_limits<int>::min()));
      {
        std::vector<int> spacing_counts_flat__;
        current_statement__ = 10;
        spacing_counts_flat__ = context__.vals_i("spacing_counts");
        current_statement__ = 10;
        pos__ = 1;
        current_statement__ = 10;
        for (int sym1__ = 1; sym1__ <= 4; ++sym1__) {
          current_statement__ = 10;
          for (int sym2__ = 1; sym2__ <= n_spac; ++sym2__) {
            current_statement__ = 10;
            stan::model::assign(spacing_counts, spacing_counts_flat__[(pos__
              - 1)], "assigning variable spacing_counts",
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
            current_statement__ = 10;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 10;
      stan::math::check_greater_or_equal(function__, "spacing_counts",
        spacing_counts, 0);
      current_statement__ = 11;
      context__.validate_dims("data initialization", "n_ftp", "int",
        std::vector<size_t>{});
      n_ftp = std::numeric_limits<int>::min();
      current_statement__ = 11;
      n_ftp = context__.vals_i("n_ftp")[(1 - 1)];
      current_statement__ = 12;
      stan::math::validate_non_negative_index("ftp_lengths", "n_ftp", n_ftp);
      current_statement__ = 13;
      context__.validate_dims("data initialization", "ftp_lengths", "int",
        std::vector<size_t>{static_cast<size_t>(n_ftp)});
      ftp_lengths = std::vector<int>(n_ftp, std::numeric_limits<int>::min());
      current_statement__ = 13;
      ftp_lengths = context__.vals_i("ftp_lengths");
      current_statement__ = 14;
      stan::math::validate_non_negative_index("ftp_prior_cover", "n_ftp",
        n_ftp);
      current_statement__ = 15;
      context__.validate_dims("data initialization", "ftp_prior_cover",
        "double", std::vector<size_t>{static_cast<size_t>(n_ftp)});
      ftp_prior_cover_data__ = Eigen::Matrix<double,-1,1>::Constant(n_ftp,
                                 std::numeric_limits<double>::quiet_NaN());
      new (&ftp_prior_cover)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(ftp_prior_cover_data__.data(),
        n_ftp);
      {
        std::vector<local_scalar_t__> ftp_prior_cover_flat__;
        current_statement__ = 15;
        ftp_prior_cover_flat__ = context__.vals_r("ftp_prior_cover");
        current_statement__ = 15;
        pos__ = 1;
        current_statement__ = 15;
        for (int sym1__ = 1; sym1__ <= n_ftp; ++sym1__) {
          current_statement__ = 15;
          stan::model::assign(ftp_prior_cover, ftp_prior_cover_flat__[(pos__
            - 1)], "assigning variable ftp_prior_cover",
            stan::model::index_uni(sym1__));
          current_statement__ = 15;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 16;
      context__.validate_dims("data initialization",
        "total_cnt_prior_dirich", "double", std::vector<size_t>{});
      total_cnt_prior_dirich = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 16;
      total_cnt_prior_dirich = context__.vals_r("total_cnt_prior_dirich")[(1
        - 1)];
      current_statement__ = 17;
      context__.validate_dims("data initialization", "bg_protect_prob",
        "double", std::vector<size_t>{});
      bg_protect_prob = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 17;
      bg_protect_prob = context__.vals_r("bg_protect_prob")[(1 - 1)];
      current_statement__ = 17;
      stan::math::check_greater_or_equal(function__, "bg_protect_prob",
        bg_protect_prob, 0);
      current_statement__ = 17;
      stan::math::check_less_or_equal(function__, "bg_protect_prob",
        bg_protect_prob, 1);
      current_statement__ = 18;
      context__.validate_dims("data initialization", "ftp_protect_min",
        "double", std::vector<size_t>{});
      ftp_protect_min = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 18;
      ftp_protect_min = context__.vals_r("ftp_protect_min")[(1 - 1)];
      current_statement__ = 19;
      context__.validate_dims("data initialization", "ftp_protect_max",
        "double", std::vector<size_t>{});
      ftp_protect_max = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 19;
      ftp_protect_max = context__.vals_r("ftp_protect_max")[(1 - 1)];
      current_statement__ = 20;
      context__.validate_dims("data initialization", "ftp_protect_mean",
        "double", std::vector<size_t>{});
      ftp_protect_mean = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 20;
      ftp_protect_mean = context__.vals_r("ftp_protect_mean")[(1 - 1)];
      current_statement__ = 21;
      context__.validate_dims("data initialization", "ftp_protect_totcount",
        "double", std::vector<size_t>{});
      ftp_protect_totcount = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 21;
      ftp_protect_totcount = context__.vals_r("ftp_protect_totcount")[(1 -
        1)];
      current_statement__ = 22;
      stan::math::validate_non_negative_index("ftp_prior_alphas", "n_ftp",
        n_ftp);
      current_statement__ = 23;
      ftp_prior_alphas_data__ = Eigen::Matrix<double,-1,1>::Constant(n_ftp,
                                  std::numeric_limits<double>::quiet_NaN());
      new (&ftp_prior_alphas)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(ftp_prior_alphas_data__.data(),
        n_ftp);
      current_statement__ = 23;
      stan::model::assign(ftp_prior_alphas,
        stan::math::multiply(ftp_prior_cover, total_cnt_prior_dirich),
        "assigning variable ftp_prior_alphas");
      current_statement__ = 24;
      ftp_protect_alpha = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 24;
      ftp_protect_alpha = (ftp_protect_totcount * ftp_protect_mean);
      current_statement__ = 25;
      ftp_protect_beta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 25;
      ftp_protect_beta = (ftp_protect_totcount * (1 - ftp_protect_mean));
      current_statement__ = 26;
      max_spacing = std::numeric_limits<int>::min();
      current_statement__ = 26;
      max_spacing = stan::math::max(spacings);
      current_statement__ = 27;
      stan::math::validate_positive_index("ftp_abundances", "n_ftp", n_ftp);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = (n_ftp - 1) + 1;
  }
  inline std::string model_name() const final {
    return "model_ftp_inference_bg_fixed";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_ftp_inference_bg_fixed_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> ftp_abundances =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_ftp, DUMMY_VAR__);
      current_statement__ = 1;
      ftp_abundances = in__.template read_constrain_simplex<
                         Eigen::Matrix<local_scalar_t__,-1,1>,
                         jacobian__>(lp__, n_ftp);
      local_scalar_t__ ftp_protect_prob = DUMMY_VAR__;
      current_statement__ = 2;
      ftp_protect_prob = in__.template read_constrain_lub<local_scalar_t__,
                           jacobian__>(ftp_protect_min, ftp_protect_max,
                           lp__);
      {
        current_statement__ = 3;
        lp_accum__.add(stan::math::dirichlet_lpdf<propto__>(ftp_abundances,
                         ftp_prior_alphas));
        current_statement__ = 4;
        lp_accum__.add(stan::math::beta_lpdf<propto__>(ftp_protect_prob,
                         ftp_protect_alpha, ftp_protect_beta));
        current_statement__ = 5;
        lp_accum__.add(ftp_model_loglik(ftp_abundances, ftp_lengths, n_ftp,
                         bg_protect_prob, ftp_protect_prob, spacings, n_spac,
                         max_spacing, spacing_counts, pstream__));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_ftp_inference_bg_fixed_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> ftp_abundances =
        Eigen::Matrix<double,-1,1>::Constant(n_ftp,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      ftp_abundances = in__.template read_constrain_simplex<
                         Eigen::Matrix<local_scalar_t__,-1,1>,
                         jacobian__>(lp__, n_ftp);
      double ftp_protect_prob = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      ftp_protect_prob = in__.template read_constrain_lub<local_scalar_t__,
                           jacobian__>(ftp_protect_min, ftp_protect_max,
                           lp__);
      out__.write(ftp_abundances);
      out__.write(ftp_protect_prob);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> ftp_abundances =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_ftp, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(ftp_abundances,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(n_ftp),
        "assigning variable ftp_abundances");
      out__.write_free_simplex(ftp_abundances);
      local_scalar_t__ ftp_protect_prob = DUMMY_VAR__;
      current_statement__ = 2;
      ftp_protect_prob = in__.read<local_scalar_t__>();
      out__.write_free_lub(ftp_protect_min, ftp_protect_max,
        ftp_protect_prob);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "ftp_abundances",
        "double", std::vector<size_t>{static_cast<size_t>(n_ftp)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "ftp_protect_prob",
        "double", std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> ftp_abundances =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_ftp, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> ftp_abundances_flat__;
        current_statement__ = 1;
        ftp_abundances_flat__ = context__.vals_r("ftp_abundances");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= n_ftp; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(ftp_abundances, ftp_abundances_flat__[(pos__ -
            1)], "assigning variable ftp_abundances",
            stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_simplex(ftp_abundances);
      local_scalar_t__ ftp_protect_prob = DUMMY_VAR__;
      current_statement__ = 2;
      ftp_protect_prob = context__.vals_r("ftp_protect_prob")[(1 - 1)];
      out__.write_free_lub(ftp_protect_min, ftp_protect_max,
        ftp_protect_prob);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"ftp_abundances", "ftp_protect_prob"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    n_ftp)},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= n_ftp; ++sym1__) {
      param_names__.emplace_back(std::string() + "ftp_abundances" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "ftp_protect_prob");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= (n_ftp - 1); ++sym1__) {
      param_names__.emplace_back(std::string() + "ftp_abundances" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "ftp_protect_prob");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"ftp_abundances\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_ftp) + "},\"block\":\"parameters\"},{\"name\":\"ftp_protect_prob\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"ftp_abundances\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string((n_ftp -1)) + "},\"block\":\"parameters\"},{\"name\":\"ftp_protect_prob\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (n_ftp + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (n_ftp + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_ftp_inference_bg_fixed_namespace::model_ftp_inference_bg_fixed;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_ftp_inference_bg_fixed_namespace::profiles__;
}
#endif
#endif
