# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcStartCoverProbs_cpp <- function(fragIDs, fragPos, modProbVec, binding_models, bgprotectprob, bgprior, ftpConfigMethod, aggrByGroup, keepStartProb, Ncpu, verbose) {
    .Call(`_footBayes_calcStartCoverProbs_cpp`, fragIDs, fragPos, modProbVec, binding_models, bgprotectprob, bgprior, ftpConfigMethod, aggrByGroup, keepStartProb, Ncpu, verbose)
}

count_spacing_freq_cpp <- function(fragIDs, fragPos, modProbVec, maxspacing, Ncpu, verbose) {
    .Call(`_footBayes_count_spacing_freq_cpp`, fragIDs, fragPos, modProbVec, maxspacing, Ncpu, verbose)
}

calculate_theor_joint_prob_cpp <- function(ftp_cover_priors, bg_protect_prob, footprint_protect_prob, max_spacing) {
    .Call(`_footBayes_calculate_theor_joint_prob_cpp`, ftp_cover_priors, bg_protect_prob, footprint_protect_prob, max_spacing)
}

